extends RefCounted

const TestAssertions = preload("res://tests/test_assertions.gd")
const ThreatDirector = preload("res://scripts/core/threat_director.gd")

func run() -> Array[String]:
	var t := TestAssertions.new()
	test_stage_to_threat_state(t)
	test_audio_cues_by_stage(t)
	test_damage_and_pursuit_profile_by_stage(t)
	test_korean_ghost_roster(t)
	return t.failures

func test_stage_to_threat_state(t: TestAssertions) -> void:
	var director := ThreatDirector.new()
	t.assert_equal(director.state_for_stage(0), "dormant", "stage 0 is dormant")
	t.assert_equal(director.state_for_stage(2), "visible", "stage 2 shows apparition")
	t.assert_equal(director.state_for_stage(4), "pursuit", "stage 4 starts pursuit")
	t.assert_equal(director.state_for_stage(5), "contested_extraction", "stage 5 contests extraction")

func test_audio_cues_by_stage(t: TestAssertions) -> void:
	var director := ThreatDirector.new()
	t.assert_true(director.audio_cues_for_stage(1).has("distant_floor_creak"), "stage 1 has subtle sound")
	t.assert_true(director.audio_cues_for_stage(3).has("door_slide_false_route"), "stage 3 has route interference cue")
	t.assert_true(director.audio_cues_for_stage(5).has("close_funeral_wail"), "stage 5 has close threat cue")

func test_damage_and_pursuit_profile_by_stage(t: TestAssertions) -> void:
	var director := ThreatDirector.new()
	t.assert_equal(director.can_damage(0), false, "stage 0 cannot damage")
	t.assert_equal(director.can_damage(1), false, "stage 1 cannot damage")
	t.assert_equal(director.can_damage(2), false, "stage 2 is warning/trap setup, not direct damage")
	t.assert_equal(director.can_damage(3), false, "stage 3 is route interference, not direct damage")
	t.assert_true(director.can_damage(4), "stage 4 spawned ghost can damage")
	t.assert_true(director.can_damage(5), "stage 5 spawned ghost can damage")
	t.assert_equal(director.can_phase_through_walls(3), false, "stage 3 does not phase through walls")
	t.assert_equal(director.can_phase_through_walls(4), true, "stage 4 wall-phasing ghost starts")
	t.assert_equal(director.damage_per_hit(0), 0, "stage 0 has no direct damage")
	t.assert_equal(director.damage_per_hit(1), 0, "stage 1 has no direct damage")
	t.assert_equal(director.damage_per_hit(2), 0, "stage 2 does not deal direct damage")
	t.assert_equal(director.damage_per_hit(3), 0, "stage 3 does not deal direct damage")
	t.assert_equal(director.damage_per_hit(4), 20, "stage 4 damage starts")
	t.assert_equal(director.damage_per_hit(5), 30, "stage 5 damage peaks")
	t.assert_true(director.damage_per_hit(4) < director.damage_per_hit(5), "stage 5 damage is higher than stage 4")
	t.assert_equal(director.attack_range(0), 0.0, "stage 0 has no attack range")
	t.assert_equal(director.attack_range(1), 0.0, "stage 1 has no attack range")
	t.assert_equal(director.attack_range(2), 0.0, "stage 2 has no attack range")
	t.assert_equal(director.attack_range(3), 0.0, "stage 3 has no attack range")
	t.assert_equal(director.attack_range(4), 2.0, "stage 4 range increases")
	t.assert_equal(director.attack_range(5), 2.4, "stage 5 range peaks")
	t.assert_equal(director.attack_interval_seconds(0), 0.0, "stage 0 has no attack interval")
	t.assert_equal(director.attack_interval_seconds(1), 0.0, "stage 1 has no attack interval")
	t.assert_equal(director.attack_interval_seconds(2), 0.0, "stage 2 has no attack interval")
	t.assert_equal(director.attack_interval_seconds(3), 0.0, "stage 3 has no attack interval")
	for stage in range(4, 6):
		t.assert_equal(director.attack_interval_seconds(stage), 2.0, "stage %d uses consistent attack cadence" % stage)
	t.assert_equal(director.pursuit_speed(0), 0.0, "stage 0 has no pursuit speed")
	t.assert_equal(director.pursuit_speed(1), 0.0, "stage 1 has no pursuit speed")
	t.assert_equal(director.pursuit_speed(2), 0.0, "stage 2 has no pursuit speed")
	t.assert_equal(director.pursuit_speed(3), 0.0, "stage 3 has no pursuit speed")
	t.assert_equal(director.pursuit_speed(4), 3.4, "stage 4 pursuit speed increases")
	t.assert_equal(director.pursuit_speed(5), 4.0, "stage 5 pursuit speed peaks")
	t.assert_equal(director.trap_trigger_resentment(0), 0, "stage 0 traps do not add resentment")
	t.assert_equal(director.trap_trigger_resentment(1), 0, "stage 1 traps do not add resentment")
	t.assert_equal(director.trap_trigger_resentment(2), 1, "stage 2 trap resentment starts")
	t.assert_equal(director.trap_trigger_resentment(3), 1, "stage 3 trap resentment stays small")
	t.assert_equal(director.trap_trigger_resentment(4), 2, "stage 4 trap resentment increases")
	t.assert_equal(director.trap_trigger_resentment(5), 3, "stage 5 trap resentment peaks")
	t.assert_equal(director.damage_per_hit(-1), 0, "damage clamps below stage 0")
	t.assert_equal(director.attack_range(-1), 0.0, "range clamps below stage 0")
	t.assert_equal(director.attack_interval_seconds(-1), 0.0, "interval clamps below stage 0")
	t.assert_equal(director.pursuit_speed(-1), 0.0, "speed clamps below stage 0")
	t.assert_equal(director.trap_trigger_resentment(-1), 0, "trap resentment clamps below stage 0")
	t.assert_equal(director.damage_per_hit(6), director.damage_per_hit(5), "damage clamps above stage 5")
	t.assert_equal(director.attack_range(6), director.attack_range(5), "range clamps above stage 5")
	t.assert_equal(director.attack_interval_seconds(6), director.attack_interval_seconds(5), "interval clamps above stage 5")
	t.assert_equal(director.pursuit_speed(6), director.pursuit_speed(5), "speed clamps above stage 5")
	t.assert_equal(director.trap_trigger_resentment(6), director.trap_trigger_resentment(5), "trap resentment clamps above stage 5")

func test_korean_ghost_roster(t: TestAssertions) -> void:
	var director := ThreatDirector.new()
	var roster: Array = director.ghost_roster()
	t.assert_true(roster.size() >= 5, "threat roster has at least five Korean ghost/yokai types")
	var ids: Array[String] = []
	for data in roster:
		t.assert_true(data.has("id"), "ghost roster entry has id")
		t.assert_true(data.has("display_name"), "ghost roster entry has display name")
		ids.append(str(data["id"]))
	t.assert_true(ids.has("sangbok_ghost"), "roster includes sangbok ghost")
	t.assert_true(ids.has("dalgyal_gwisin"), "roster includes dalgyal gwisin")
	t.assert_true(ids.has("dokkaebi"), "roster includes dokkaebi")
	t.assert_true(ids.has("eoduksini"), "roster includes eoduksini")
	t.assert_true(ids.has("well_spirit"), "roster includes well spirit")
	t.assert_equal(director.ghost_type_for_stage(3), "", "stage 3 does not pick the wall-phasing hunter")
	t.assert_equal(director.ghost_type_for_stage(4), "sangbok_ghost", "stage 4 activates sangbok ghost")
	t.assert_equal(director.ghost_type_for_stage(5), "dalgyal_gwisin", "stage 5 swaps to stronger ghost type")
